name:                dice-monad
version:             0.1.0.0
github:              "superchig/dice-monad"
license:             GPL-3
author:              "Christopher Chang"
maintainer:          "chiggiechang@gmail.com"
copyright:           "2021 Christopher Chang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dice-monad#readme>

dependencies:
- base >= 4.7 && < 5
- array
- random
- mwc-random

library:
  source-dirs: src

executables:
  dice-monad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dice-monad

tests:
  dice-monad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dice-monad
